"""Add missing tables

Revision ID: 0f734d5226ff
Revises: f79883fd8cab
Create Date: 2024-11-08 18:39:10.016068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f734d5226ff'
down_revision: Union[str, None] = 'f79883fd8cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp_code', sa.String(), nullable=False),
    sa.Column('expiration_time', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_email'), 'otps', ['email'], unique=False)
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealership_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'DEALER', 'SALES_EXECUTIVE', 'FINANCE', 'RTO', 'CUSTOMER', name='roleenum'), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('variant', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('ex_showroom_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('tax', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('insurance', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('tp_registration', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('man_accessories', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('optional_accessories', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealership_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='now()', nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('dealership_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealership_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DEALER', 'SALES_EXECUTIVE', 'FINANCE', 'RTO', 'CUSTOMER', name='roleenum'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealership_roles_id'), 'dealership_roles', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealership_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('payment_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('suggested_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealership_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggested_roles_id'), 'suggested_roles', ['id'], unique=False)
    op.add_column('branches', sa.Column('name', sa.String(), nullable=False))
    op.add_column('branches', sa.Column('location', sa.String(), nullable=True))
    op.add_column('branches', sa.Column('created_at', sa.TIMESTAMP(), server_default='now()', nullable=True))
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.add_column('dealerships', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('dealerships', sa.Column('created_at', sa.TIMESTAMP(), server_default='now()', nullable=True))
    op.add_column('dealerships', sa.Column('address', sa.String(), nullable=False))
    op.add_column('dealerships', sa.Column('contact_number', sa.String(), nullable=False))
    op.add_column('dealerships', sa.Column('num_employees', sa.Integer(), nullable=False))
    op.add_column('dealerships', sa.Column('num_branches', sa.Integer(), nullable=False))
    op.add_column('dealerships', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.alter_column('dealerships', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_dealerships_id'), 'dealerships', ['id'], unique=False)
    op.create_unique_constraint(None, 'dealerships', ['contact_email'])
    op.create_foreign_key(None, 'dealerships', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dealerships', type_='foreignkey')
    op.drop_constraint(None, 'dealerships', type_='unique')
    op.drop_index(op.f('ix_dealerships_id'), table_name='dealerships')
    op.alter_column('dealerships', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('dealerships', 'creator_id')
    op.drop_column('dealerships', 'num_branches')
    op.drop_column('dealerships', 'num_employees')
    op.drop_column('dealerships', 'contact_number')
    op.drop_column('dealerships', 'address')
    op.drop_column('dealerships', 'created_at')
    op.drop_column('dealerships', 'contact_email')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_column('branches', 'created_at')
    op.drop_column('branches', 'location')
    op.drop_column('branches', 'name')
    op.drop_index(op.f('ix_suggested_roles_id'), table_name='suggested_roles')
    op.drop_table('suggested_roles')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_dealership_roles_id'), table_name='dealership_roles')
    op.drop_table('dealership_roles')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_index(op.f('ix_otps_email'), table_name='otps')
    op.drop_table('otps')
    # ### end Alembic commands ###
