"""Add creator_id to Dealership and created_dealership to User

Revision ID: 387a00fdfa82
Revises: 66b6f59676f1
Create Date: 2024-11-07 03:06:56.745221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387a00fdfa82'
down_revision: Union[str, None] = '66b6f59676f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealerships', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'dealerships', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dealerships', type_='foreignkey')
    op.drop_column('dealerships', 'creator_id')
    # ### end Alembic commands ###
