"""Change foreign key relationships

Revision ID: ae09f9e4d644
Revises: e6d7d2cf5cf4
Create Date: 2024-11-04 16:55:05.596489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae09f9e4d644'
down_revision: Union[str, None] = 'e6d7d2cf5cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('dealership_id', sa.Integer(), nullable=True))
    op.drop_constraint('payments_user_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'dealerships', ['dealership_id'], ['id'], ondelete='CASCADE')
    op.drop_column('payments', 'user_id')
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('payments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_user_id_fkey', 'payments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('payments', 'dealership_id')
    # ### end Alembic commands ###
