"""add num_branches coloumn to dealerships table

Revision ID: ef5cd34ab733
Revises: 40edce1d4978
Create Date: 2024-11-07 22:21:06.653780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5cd34ab733'
down_revision: Union[str, None] = '40edce1d4978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealerships', sa.Column('num_branches', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dealerships', 'num_branches')
    # ### end Alembic commands ###